### ISSUE TITLE
Error in calculation result

### ISSUE THREAD

**Issue by onefanwu** [CGCL-codes/MHSim#2]
Hi, I found an error in the calculation when I tested the simple GEMM.
I wish you can point out my mistake. Here is the test procedure.

------------------------------------------------------------------------ example -----------------------------------------------------------------
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>

#include "Memristor_CU.h"
#include "Memristor_CU.cpp"

extern "C" {
#include <cblas.h>
}

using namespace std;

int main() {

  unsigned int M = 3, N = 3, K = 3;

  float *A = new float[M * K], *B = new float[K * N], *C = new float[M * N], *D = new float[M * N];

  char comma;

  for (int i = 0; i < M * K; i++) A[i] = i;
  /*
  0 1 2
  3 4 5
  6 7 8
  */

  for (int i = 0; i < K * N; i++) B[i] = 2;
  /*
  2 2 2
  2 2 2
  2 2 2
  */

  for (int i = 0; i < M * N; i++) {
    C[i] = 0.;
    D[i] = 0.;
  }

  Memristor_CU<RealDevice> *mcu =
      new Memristor_CU<RealDevice>(M, K, A, IMW, 2, 128, 128, 8);

  // CIM: A * B --> C
  mcu->memristor_mm(B, N, C, 1., 0., 16);
  mcu->ReadLatency(16);
  mcu->Energy(B, N);

  // CPU: A * B2 --> D, https://developer.apple.com/documentation/accelerate/1513264-cblas_sgemm
  cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, M, N, K, 1., A, K, B, N, 0., D, N);  // for cpu

  for (int i = 0; i < 9; i++) {
    printf("C = %.4e  D = %.4e \n", C[i], D[i]);
  }

  double writeLatency = 0.;
  for (int k = 0; k < K; k++) {
    writeLatency += mcu->getWriteLatency(k);
  }

  printf("ReadLatency = %.5e   readEnergy = %.5e   writeLatency = %.5e   writeEnergy = %.5e\n",
   mcu->getLatency(), mcu->getReadEnergy(), writeLatency, mcu->getWriteEnergy());

  delete[] A;
  delete[] B;
  delete[] D;
  delete[] C;
  delete mcu;
  return 0;
}

------------------------------------------------------------------------ example -----------------------------------------------------------------

------------------------------------------------------------------------ output -----------------------------------------------------------------
[H] Starting zsim, built Tue Mar 29 11:34:25 UTC 2022 (rev no git repo)
[H] Creating global segment, 1024 MBs
[H] Global segment shmid = 229376
[H] Deadlock detection ON
[S 0] Started instance
[S 0] Started RR scheduler, quantum=10000 phases
[S 0] Hierarchy: [ l1i-0 l1d-0 ] -> l2-0
[S 0] Hierarchy: [ l1i-1 l1d-1 ] -> l2-1
[S 0] Hierarchy: [ l1i-2 l1d-2 ] -> l2-2
[S 0] Hierarchy: [ l1i-3 l1d-3 ] -> l2-3
[S 0] Hierarchy: [ l2-0 l2-1 l2-2 l2-3 ] -> l3-0b0..l3-0b5
[S 0] Initialized system
[S 0] HDF5 backend: Opening /home/wyf/X-Store/MHSim/zsim/zsim.h5
[S 0] HDF5 backend: Created table, 3928 bytes/record, 267 records/write
[S 0] HDF5 backend: Opening /home/wyf/X-Store/MHSim/zsim/zsim-ev.h5
[S 0] HDF5 backend: Created table, 3928 bytes/record, 34 records/write
[S 0] HDF5 backend: Opening /home/wyf/X-Store/MHSim/zsim/zsim-cmp.h5
[S 0] HDF5 backend: Created table, 2320 bytes/record, 1 records/write
[S 0] Initialization complete
[H] Attached to global heap
[S 0] Started process, PID 54354
[S 0] procMask: 0x0
[S 0] [0] Adjusting clocks, domain 0, de-ffwd 0
[S 0] vDSO info initialized
[S 0] Thread 0 starting
[S 0] Started scheduler watchdog thread
[S 0] Started contention simulation thread 0
[S 0] FF control Thread TID 54357
[S 0] [0] Post-patching SYS_sched_getaffinity size 8 cpuset 0x55555577ce70
[S 0] Thread 4 starting
[S 0] Thread 5 starting
[S 0] Thread 6 starting
[S 0] Detected possible stall due to fake leaves (2 current)
[S 0]  [0/6] accept (202) @ 0x7fffdf9e9111
[S 0]  [0/5] accept (202) @ 0x7fffdf9e9111
[S 0] Detected possible stall due to fake leaves (1 current)
[S 0]  [0/5] accept (202) @ 0x7fffdf9e9111
[S 0] Blacklisting from future fake leaves: [0] accept @ 0x7fffdf9e9111 | arg0 0x55555577ee14 arg1 0x80
[S 0] Detected possible stall due to fake leaves (3 current)
[S 0]  [0/5] accept (202) @ 0x7fffdf9e8f4c
[S 0]  [0/4] accept (202) @ 0x7fffdf9e8f4c
[S 0]  [0/6] accept (202) @ 0x7fffdf9e8f4c
[S 0] Detected possible stall due to fake leaves (2 current)
[S 0]  [0/4] accept (202) @ 0x7fffdf9e8f4c
[S 0]  [0/6] accept (202) @ 0x7fffdf9e8f4c
[S 0] Detected possible stall due to fake leaves (1 current)
[S 0]  [0/6] accept (202) @ 0x7fffdf9e8f4c
[S 0] Blacklisting from future fake leaves: [0] accept @ 0x7fffdf9e8f4c | arg0 0x55555577ed04 arg1 0x80
C = 2.1518e+01  D = 6.0000e+00 
C = 2.6862e+01  D = 6.0000e+00 
C = 4.4466e+01  D = 6.0000e+00 
C = 2.1518e+01  D = 2.4000e+01 
C = 2.6862e+01  D = 2.4000e+01 
C = 4.4466e+01  D = 2.4000e+01 
C = 2.1518e+01  D = 4.2000e+01 
C = 2.6862e+01  D = 4.2000e+01 
C = 4.4466e+01  D = 4.2000e+01 
ReadLatency = 1.03092e-03   readEnergy = 4.45081e-07   writeLatency = 1.49000e-05   writeEnergy = 1.12338e-10
[S 0] Thread 0 finished
[S 0] Thread 4 finished
[S 0] Thread 5 finished
[S 0] Thread 6 finished
[S 0] Finished, code 0
[S 0] Dumping termination stats
[H] Child 54353 done
[H] All children done, exiting
------------------------------------------------------------------------ output -----------------------------------------------------------------

![image](https://user-images.githubusercontent.com/96245396/161362868-e628edf7-0dbe-4e81-98b8-ae21c69ee201.png)

**Comment by jhxu001** [comment]
From your codes, I find that you are calculating A*B with IMW. However, the code **new Memristor_CU(M, K, A, IMW, 2, 128, 128, 8); ** means that you map A as a weight matrix, while the weight matrix is located at the latter. So your codes have implemented a matrix multiplication "B*A" instead of "A*B".
To implement "A*B" with "IMW", you should write the code like the following:
Memristor_CU *mcu =
new Memristor_CU(N, K, B, IMW, 2, 128, 128, 8);

// CIM: A * B --> C
mcu->memristor_mm(A, M, C, 1., 0.);

**Comment by onefanwu** [comment]
Thank you very much for your reply! My corrected output is shown in "output1" below, there is a non-negligible error between **C** and the real result **D**, is this normal? After replacing class _RealDevice_ with class _IdealDevice_ when I initialize _Memristor_CU_, the output is shown as "output2". Is the error in "output1" all is caused by the device?

--------------- output1 -------------------------
// Memristor_CU\<RealDevice> *mcu = new Memristor_CU\<RealDevice> (N, K, B, IMW, 2, 128, 128, 8);
// mcu->memristor_mm(A, M, C, 1., 0.);

C = 7.7100e+00  D = 6.0000e+00 
C = 7.7100e+00  D = 6.0000e+00 
C = 7.7100e+00  D = 6.0000e+00 
C = 3.0840e+01  D = 2.4000e+01 
C = 3.0840e+01  D = 2.4000e+01 
C = 3.0840e+01  D = 2.4000e+01 
C = 5.3970e+01  D = 4.2000e+01 
C = 5.3970e+01  D = 4.2000e+01 
C = 5.3970e+01  D = 4.2000e+01 

--------------- output2 -------------------------
// Memristor_CU\<IdealDevice> *mcu = new Memristor_CU\<IdealDevice> (N, K, B, IMW, 2, 128, 128, 8);
// mcu->memristor_mm(A, M, C, 1., 0.);

C = 6.1399e+00  D = 6.0000e+00 
C = 6.1399e+00  D = 6.0000e+00 
C = 6.1399e+00  D = 6.0000e+00 
C = 2.4560e+01  D = 2.4000e+01 
C = 2.4560e+01  D = 2.4000e+01 
C = 2.4560e+01  D = 2.4000e+01 
C = 4.2979e+01  D = 4.2000e+01 
C = 4.2979e+01  D = 4.2000e+01 
C = 4.2979e+01  D = 4.2000e+01

**Comment by jhxu001** [comment]
The error in "output1" is caused by the device. The default device that NeuroSim chooses (Ag:a-Si) shows great non-linearity, which leads to serious errors. You can set the properties of "RealDevice" in "Cell.cpp" manually with the device table provided in NeuroSim (The "TaOx/HfOx" device shows tiny errors).

**Comment by onefanwu** [comment]
I got it! Thank you very much for answering my questions during the holidays.
