### ISSUE TITLE
Question about mvm cycles and store instrcution

### ISSUE THREAD

**Issue by onefanwu** [CGCL-codes/MHSim#3]
## Problem description
Hi MHSim maintainers, I have some questions about the mvm cycles and would like to seek your answers. When I perform the multiplication of vector B (row size:1, column size: 128) and matrix A (row size:128, column size: 256, mapped to PEs) in full system mode on MHSim, I get MBA mem access is 100008 and MBA mvm cycle is 65513. When the number of columns of matrix A is expanded to 5120 (= 40 * 128), I get MBA mem access is 1992104 and MBA mvm cycle is 65513. I am confused why the MBA mvm cycles are kept constant?

At first, I presumed that A's PEs are parallel when doing B*A whether it occupies 2 PEs or 40 PEs, so the mvm cycle is a constant. However, when I only counted mapping A to PEs, I found that the MBA mem access of A in the two tests mentioned above were 99584 and 1991680 respectively. this means that the mem accesses only increased by 424 cycles when the compute instruction was performed, but obviously when the size of A became larger the computation result should also becomes larger.

Another question is about the calculation results, MHSim uses Intel Pin to capture the cblas_sgemm function, which returns accurate CPU results (no precision errors). So is the modified zsim only responsible for simulating the performance model?

**Comment by onefanwu** [comment]
I think this result happens because the right number of load/store instructions are not generated according to the size of matrix A. In line 308 and lines 324-324 of the file [tile.cpp](https://github.com/CGCL-codes/MHSim/blob/master/zsim/src/MHSim/tile.cpp), I found that the load/store instruction generation is independent of the parameter M, which is the number of columns of the matrix A. I am curious why the parameter M is independent of load/store instruction generation? I may have misunderstood, but I hope you can give me an answer.

**Comment by onefanwu** [comment]
@jhxu001 , Hi, I seem to figure out the answer in your code. In lines 324-324 of the file [tile.cpp](https://github.com/CGCL-codes/MHSim/blob/master/zsim/src/MHSim/tile.cpp), you seem to incorrectly associate the store instruction execution with the parameter N, when in fact it should be M. N is the number of columns of the input matrix, while M is the number of columns of the mapped matrix. When I keep expanding the number of columns of matrix A, I find that the store instruction is always executed only 1 time, because ii*lineSize < accReq.N can be satisfied only once.

**Comment by onefanwu** [comment]
In the lines 324-324 of the file [tile.cpp](https://github.com/CGCL-codes/MHSim/blob/master/zsim/src/MHSim/tile.cpp), I found that store instruction generation is related to parameter N, but parameter N is the number of columns of the input matrix. Maybe ii*lineSize should not be less than accReq.N but accReq.M, because the parameter M is the number of columns of the mapped matrix. When I expand the number of columns of matrix A to 40 * 128, I find that only one store instruction is executed.

**Comment by jhxu001** [comment]
You are right. The parameter N should be M in line 324.

**Comment by onefanwu** [comment]
@jhxu001 Thank you for your reply, I still have some doubts and I wonder if I can discuss this with you further. I have sent you an email by gmail.
